using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace HCommons.Reflection.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed class RuntimeTypeCacheGenerator : IIncrementalGenerator {
    const string GenerateAttributeName = "HCommons.Reflection.GenerateRuntimeTypeCacheAttribute";
    const string GeneratedTypesAttributeName = "HCommons.Reflection.RuntimeTypeCacheGeneratedTypesAttribute";
    const string TargetAttributeName = "HCommons.Reflection.RuntimeTypeCacheSourceGenerationTargetAttribute";
    const int CatalogChunkSize = 128;

    static readonly DiagnosticDescriptor s_inaccessibleType = new(
        "HCRTCGEN001",
        "Runtime type cache query requires reflection fallback",
        "The generated catalog for base type '{0}' is incomplete because type '{1}' cannot be referenced from generated assembly-level code",
        "HCommons.Reflection.SourceGeneration",
        DiagnosticSeverity.Info,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var generation = context.CompilationProvider.Select(Generate);

        context.RegisterSourceOutput(generation, static (productionContext, result) => {
            foreach (var diagnostic in result.Diagnostics) {
                productionContext.ReportDiagnostic(diagnostic);
            }

            if (result.Source is not null) {
                productionContext.AddSource(
                    "RuntimeTypeCache.Catalogs.g.cs",
                    SourceText.From(result.Source, Encoding.UTF8));
            }
        });
    }

    static GenerationResult Generate(Compilation compilation, CancellationToken cancellationToken) {
        var generateAttribute = compilation.GetTypeByMetadataName(GenerateAttributeName);
        var generatedTypesAttribute = compilation.GetTypeByMetadataName(GeneratedTypesAttributeName);
        var targetAttribute = compilation.GetTypeByMetadataName(TargetAttributeName);

        if (generateAttribute is null || generatedTypesAttribute is null || targetAttribute is null) {
            return GenerationResult.Empty;
        }

        var declaredTypes = GetDeclaredTypes(compilation, cancellationToken);
        var queries = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        CollectInvocationQueries(compilation, targetAttribute, queries, cancellationToken);
        CollectAnnotatedQueries(declaredTypes, generateAttribute, queries);
        CollectReferencedQueries(compilation, generatedTypesAttribute, queries);

        if (queries.Count == 0) {
            return GenerationResult.Empty;
        }

        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");

        foreach (var baseType in queries.OrderBy(GetSortName, StringComparer.Ordinal)) {
            cancellationToken.ThrowIfCancellationRequested();

            if (!CanRenderTypeOf(baseType)) {
                diagnostics.Add(Diagnostic.Create(
                    s_inaccessibleType,
                    GetLocation(baseType),
                    GetSortName(baseType),
                    GetSortName(baseType)));
                continue;
            }

            var matches = declaredTypes
                .Where(type => IsAssignableTo(compilation, type, baseType))
                .OrderBy(GetSortName, StringComparer.Ordinal)
                .ToArray();
            var renderableMatches = new List<INamedTypeSymbol>(matches.Length);
            var isComplete = true;

            foreach (var match in matches) {
                if (CanRenderTypeOf(match)) {
                    renderableMatches.Add(match);
                    continue;
                }

                isComplete = false;
                diagnostics.Add(Diagnostic.Create(
                    s_inaccessibleType,
                    GetLocation(match),
                    GetSortName(baseType),
                    GetSortName(match)));
            }

            if (renderableMatches.Count == 0) {
                AppendCatalog(source, baseType, isComplete, Array.Empty<INamedTypeSymbol>());
                continue;
            }

            for (var start = 0; start < renderableMatches.Count; start += CatalogChunkSize) {
                var count = Math.Min(CatalogChunkSize, renderableMatches.Count - start);
                AppendCatalog(source, baseType, isComplete, renderableMatches.GetRange(start, count));
            }
        }

        return new GenerationResult(source.ToString(), diagnostics.ToImmutable());
    }

    static List<INamedTypeSymbol> GetDeclaredTypes(
        Compilation compilation,
        CancellationToken cancellationToken) {
        var types = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var syntaxTree in compilation.SyntaxTrees.OrderBy(tree => tree.FilePath, StringComparer.Ordinal)) {
            cancellationToken.ThrowIfCancellationRequested();
            var semanticModel = compilation.GetSemanticModel(syntaxTree);
            var root = syntaxTree.GetRoot(cancellationToken);

            foreach (var node in root.DescendantNodes()) {
                INamedTypeSymbol? type = node switch {
                    BaseTypeDeclarationSyntax declaration =>
                        semanticModel.GetDeclaredSymbol(declaration, cancellationToken) as INamedTypeSymbol,
                    DelegateDeclarationSyntax declaration =>
                        semanticModel.GetDeclaredSymbol(declaration, cancellationToken),
                    _ => null,
                };

                if (type is not null && !type.IsImplicitlyDeclared) {
                    types.Add(type);
                }
            }
        }

        return types.OrderBy(GetSortName, StringComparer.Ordinal).ToList();
    }

    static void CollectInvocationQueries(
        Compilation compilation,
        INamedTypeSymbol targetAttribute,
        HashSet<INamedTypeSymbol> queries,
        CancellationToken cancellationToken) {
        var methodBodies = new Dictionary<IMethodSymbol, MethodBodyInfo>(SymbolEqualityComparer.Default);
        var sourceInvocations = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);

        foreach (var syntaxTree in compilation.SyntaxTrees.OrderBy(tree => tree.FilePath, StringComparer.Ordinal)) {
            cancellationToken.ThrowIfCancellationRequested();
            var semanticModel = compilation.GetSemanticModel(syntaxTree);
            var root = syntaxTree.GetRoot(cancellationToken);

            foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>()) {
                var operation = semanticModel.GetOperation(invocation, cancellationToken) as IInvocationOperation;
                if (operation is null) {
                    continue;
                }

                var containingMethod = semanticModel.GetEnclosingSymbol(
                    invocation.SpanStart,
                    cancellationToken) as IMethodSymbol;
                var containingDefinition = containingMethod is null
                    ? null
                    : GetMethodDefinition(containingMethod);
                var marker = operation.TargetMethod.GetAttributes().FirstOrDefault(attribute =>
                    SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, targetAttribute));
                if (TryGetQueryType(operation, marker) is { } queryType) {
                    if (queryType is INamedTypeSymbol namedType && IsConcreteQueryType(namedType)) {
                        queries.Add(namedType);
                    }

                    if (containingDefinition is not null) {
                        GetOrCreateMethodBody(methodBodies, containingDefinition)
                            .QueryTypes.Add(queryType);
                    }
                }

                var targetDefinition = GetMethodDefinition(operation.TargetMethod);
                if (!IsSourceMethod(targetDefinition)) {
                    continue;
                }

                sourceInvocations.Add(operation.TargetMethod);
                if (containingDefinition is not null) {
                    GetOrCreateMethodBody(methodBodies, containingDefinition)
                        .Invocations.Add(operation.TargetMethod);
                }
            }
        }

        var queryMethods = GetMethodsReachingQuery(methodBodies, cancellationToken);
        foreach (var invocation in sourceInvocations) {
            cancellationToken.ThrowIfCancellationRequested();
            var definition = GetMethodDefinition(invocation);
            if (!queryMethods.Contains(definition)) {
                continue;
            }

            var substitutions = CreateTypeSubstitutions(
                compilation,
                invocation,
                parentSubstitutions: null);
            CollectMethodQueries(
                compilation,
                definition,
                substitutions,
                methodBodies,
                queryMethods,
                new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default),
                queries,
                cancellationToken);
        }
    }

    static ITypeSymbol? TryGetQueryType(
        IInvocationOperation operation,
        AttributeData? marker) {
        if (marker is null || marker.ConstructorArguments.Length != 2) {
            return null;
        }

        var sourceValue = marker.ConstructorArguments[0].Value as int?;
        var indexValue = marker.ConstructorArguments[1].Value as int?;
        if (sourceValue is null || indexValue is null || indexValue < 0) {
            return null;
        }

        return sourceValue.Value switch {
            0 => GetGenericQueryType(operation.TargetMethod, indexValue.Value),
            1 => GetMethodArgumentQueryType(operation, indexValue.Value),
            _ => null,
        };
    }

    static MethodBodyInfo GetOrCreateMethodBody(
        Dictionary<IMethodSymbol, MethodBodyInfo> methodBodies,
        IMethodSymbol method) {
        if (!methodBodies.TryGetValue(method, out var methodBody)) {
            methodBody = new MethodBodyInfo();
            methodBodies.Add(method, methodBody);
        }

        return methodBody;
    }

    static HashSet<IMethodSymbol> GetMethodsReachingQuery(
        IReadOnlyDictionary<IMethodSymbol, MethodBodyInfo> methodBodies,
        CancellationToken cancellationToken) {
        var callers = new Dictionary<IMethodSymbol, HashSet<IMethodSymbol>>(SymbolEqualityComparer.Default);
        var queryMethods = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
        var pending = new Queue<IMethodSymbol>();

        foreach (var pair in methodBodies) {
            cancellationToken.ThrowIfCancellationRequested();
            if (pair.Value.QueryTypes.Count > 0 && queryMethods.Add(pair.Key)) {
                pending.Enqueue(pair.Key);
            }

            foreach (var invocation in pair.Value.Invocations) {
                var target = GetMethodDefinition(invocation);
                if (!callers.TryGetValue(target, out var targetCallers)) {
                    targetCallers = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
                    callers.Add(target, targetCallers);
                }

                targetCallers.Add(pair.Key);
            }
        }

        while (pending.Count > 0) {
            cancellationToken.ThrowIfCancellationRequested();
            var target = pending.Dequeue();
            if (!callers.TryGetValue(target, out var targetCallers)) {
                continue;
            }

            foreach (var caller in targetCallers) {
                if (queryMethods.Add(caller)) {
                    pending.Enqueue(caller);
                }
            }
        }

        return queryMethods;
    }

    static void CollectMethodQueries(
        Compilation compilation,
        IMethodSymbol method,
        IReadOnlyDictionary<ITypeParameterSymbol, ITypeSymbol> substitutions,
        IReadOnlyDictionary<IMethodSymbol, MethodBodyInfo> methodBodies,
        HashSet<IMethodSymbol> queryMethods,
        HashSet<IMethodSymbol> activeMethods,
        HashSet<INamedTypeSymbol> queries,
        CancellationToken cancellationToken) {
        cancellationToken.ThrowIfCancellationRequested();
        if (!activeMethods.Add(method)) {
            return;
        }

        try {
            if (!methodBodies.TryGetValue(method, out var methodBody)) {
                return;
            }

            foreach (var queryType in methodBody.QueryTypes) {
                var substitutedType = SubstituteType(compilation, queryType, substitutions);
                if (substitutedType is INamedTypeSymbol namedType && IsConcreteQueryType(namedType)) {
                    queries.Add(namedType);
                }
            }

            foreach (var invocation in methodBody.Invocations) {
                var target = GetMethodDefinition(invocation);
                if (!queryMethods.Contains(target)) {
                    continue;
                }

                var targetSubstitutions = CreateTypeSubstitutions(
                    compilation,
                    invocation,
                    substitutions);
                CollectMethodQueries(
                    compilation,
                    target,
                    targetSubstitutions,
                    methodBodies,
                    queryMethods,
                    activeMethods,
                    queries,
                    cancellationToken);
            }
        }
        finally {
            activeMethods.Remove(method);
        }
    }

    static Dictionary<ITypeParameterSymbol, ITypeSymbol> CreateTypeSubstitutions(
        Compilation compilation,
        IMethodSymbol method,
        IReadOnlyDictionary<ITypeParameterSymbol, ITypeSymbol>? parentSubstitutions) {
        var definition = GetMethodDefinition(method);
        var substitutions = new Dictionary<ITypeParameterSymbol, ITypeSymbol>(SymbolEqualityComparer.Default);

        AddContainingTypeSubstitutions(
            compilation,
            definition.ContainingType,
            method.ContainingType,
            parentSubstitutions,
            substitutions);
        AddTypeParameterSubstitutions(
            compilation,
            definition.TypeParameters,
            method.TypeArguments,
            parentSubstitutions,
            substitutions);

        return substitutions;
    }

    static void AddContainingTypeSubstitutions(
        Compilation compilation,
        INamedTypeSymbol? definition,
        INamedTypeSymbol? constructedType,
        IReadOnlyDictionary<ITypeParameterSymbol, ITypeSymbol>? parentSubstitutions,
        Dictionary<ITypeParameterSymbol, ITypeSymbol> substitutions) {
        if (definition is null || constructedType is null) {
            return;
        }

        AddContainingTypeSubstitutions(
            compilation,
            definition.ContainingType,
            constructedType.ContainingType,
            parentSubstitutions,
            substitutions);
        AddTypeParameterSubstitutions(
            compilation,
            definition.TypeParameters,
            constructedType.TypeArguments,
            parentSubstitutions,
            substitutions);
    }

    static void AddTypeParameterSubstitutions(
        Compilation compilation,
        ImmutableArray<ITypeParameterSymbol> parameters,
        ImmutableArray<ITypeSymbol> arguments,
        IReadOnlyDictionary<ITypeParameterSymbol, ITypeSymbol>? parentSubstitutions,
        Dictionary<ITypeParameterSymbol, ITypeSymbol> substitutions) {
        var count = Math.Min(parameters.Length, arguments.Length);
        for (var index = 0; index < count; index++) {
            substitutions[parameters[index]] = parentSubstitutions is null
                ? arguments[index]
                : SubstituteType(compilation, arguments[index], parentSubstitutions);
        }
    }

    static ITypeSymbol SubstituteType(
        Compilation compilation,
        ITypeSymbol type,
        IReadOnlyDictionary<ITypeParameterSymbol, ITypeSymbol> substitutions) {
        if (type is ITypeParameterSymbol typeParameter &&
            substitutions.TryGetValue(typeParameter, out var substitution)) {
            return SymbolEqualityComparer.Default.Equals(type, substitution)
                ? substitution
                : SubstituteType(compilation, substitution, substitutions);
        }

        return type switch {
            INamedTypeSymbol namedType => SubstituteNamedType(compilation, namedType, substitutions),
            IArrayTypeSymbol arrayType => compilation.CreateArrayTypeSymbol(
                SubstituteType(compilation, arrayType.ElementType, substitutions),
                arrayType.Rank),
            IPointerTypeSymbol pointerType => compilation.CreatePointerTypeSymbol(
                SubstituteType(compilation, pointerType.PointedAtType, substitutions)),
            _ => type,
        };
    }

    static INamedTypeSymbol SubstituteNamedType(
        Compilation compilation,
        INamedTypeSymbol type,
        IReadOnlyDictionary<ITypeParameterSymbol, ITypeSymbol> substitutions) {
        var definition = type.OriginalDefinition;
        if (type.ContainingType is not null) {
            var containingType = SubstituteNamedType(compilation, type.ContainingType, substitutions);
            definition = containingType
                .GetTypeMembers(type.Name, type.Arity)
                .FirstOrDefault(candidate => SymbolEqualityComparer.Default.Equals(
                    candidate.OriginalDefinition,
                    type.OriginalDefinition)) ?? definition;
        }

        if (type.Arity == 0) {
            return definition;
        }

        var typeArguments = type.TypeArguments
            .Select(argument => SubstituteType(compilation, argument, substitutions))
            .ToArray();
        return definition.Construct(typeArguments);
    }

    static IMethodSymbol GetMethodDefinition(IMethodSymbol method) =>
        (method.ReducedFrom ?? method).OriginalDefinition;

    static bool IsSourceMethod(IMethodSymbol method) => method.DeclaringSyntaxReferences.Length > 0;

    static ITypeSymbol? GetGenericQueryType(IMethodSymbol method, int index) =>
        index < method.TypeArguments.Length ? method.TypeArguments[index] : null;

    static ITypeSymbol? GetMethodArgumentQueryType(IInvocationOperation operation, int parameterIndex) {
        var argument = operation.Arguments.FirstOrDefault(candidate =>
            candidate.Parameter?.Ordinal == parameterIndex);
        if (argument is null) {
            return null;
        }

        IOperation value = argument.Value;
        while (value is IConversionOperation conversion) {
            value = conversion.Operand;
        }

        return value is ITypeOfOperation typeOf ? typeOf.TypeOperand : null;
    }

    static void CollectAnnotatedQueries(
        IEnumerable<INamedTypeSymbol> declaredTypes,
        INamedTypeSymbol generateAttribute,
        HashSet<INamedTypeSymbol> queries) {
        foreach (var type in declaredTypes) {
            if (!IsConcreteQueryType(type)) {
                continue;
            }

            if (type.GetAttributes().Any(attribute =>
                    SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, generateAttribute))) {
                queries.Add(type);
            }
        }
    }

    static void CollectReferencedQueries(
        Compilation compilation,
        INamedTypeSymbol generatedTypesAttribute,
        HashSet<INamedTypeSymbol> queries) {
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols) {
            foreach (var attribute in assembly.GetAttributes()) {
                if (!SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, generatedTypesAttribute) ||
                    attribute.ConstructorArguments.Length == 0 ||
                    attribute.ConstructorArguments[0].Value is not INamedTypeSymbol baseType ||
                    !IsConcreteQueryType(baseType)) {
                    continue;
                }

                queries.Add(baseType);
            }
        }
    }

    static bool IsConcreteQueryType(INamedTypeSymbol type) =>
        !type.IsUnboundGenericType && !ContainsTypeParameter(type);

    static bool ContainsTypeParameter(ITypeSymbol type) {
        if (type.TypeKind == TypeKind.TypeParameter) {
            return true;
        }

        if (type is not INamedTypeSymbol namedType) {
            return false;
        }

        foreach (var typeArgument in namedType.TypeArguments) {
            if (ContainsTypeParameter(typeArgument)) {
                return true;
            }
        }

        return namedType.ContainingType is not null && ContainsTypeParameter(namedType.ContainingType);
    }

    static bool IsAssignableTo(Compilation compilation, INamedTypeSymbol type, INamedTypeSymbol baseType) {
        if (SymbolEqualityComparer.Default.Equals(type, baseType)) {
            return false;
        }

        if (compilation is not CSharpCompilation csharpCompilation) {
            return false;
        }

        var conversion = csharpCompilation.ClassifyConversion(type, baseType);
        return conversion.IsImplicit &&
               (conversion.IsReference || conversion.IsBoxing || conversion.IsIdentity);
    }

    static bool CanRenderTypeOf(INamedTypeSymbol type) {
        for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType) {
            if (IsFileLocal(current)) {
                return false;
            }

            if (current.ContainingType is null) {
                if (current.DeclaredAccessibility is not Accessibility.Public and not Accessibility.Internal) {
                    return false;
                }

                continue;
            }

            if (current.DeclaredAccessibility is not Accessibility.Public and
                not Accessibility.Internal and
                not Accessibility.ProtectedOrInternal) {
                return false;
            }
        }

        return true;
    }

    static bool IsFileLocal(INamedTypeSymbol type) {
        foreach (var syntaxReference in type.DeclaringSyntaxReferences) {
            if (syntaxReference.GetSyntax() is TypeDeclarationSyntax declaration &&
                declaration.Modifiers.Any(modifier => modifier.ValueText == "file")) {
                return true;
            }
        }

        return false;
    }

    static void AppendCatalog(
        StringBuilder source,
        INamedTypeSymbol baseType,
        bool isComplete,
        IReadOnlyList<INamedTypeSymbol> derivedTypes) {
        source.Append("[assembly: global::HCommons.Reflection.RuntimeTypeCacheGeneratedTypesAttribute(typeof(");
        source.Append(RenderTypeOf(baseType));
        source.Append("), ");
        source.Append(isComplete ? "true" : "false");

        foreach (var type in derivedTypes) {
            source.Append(", typeof(");
            source.Append(RenderTypeOf(type));
            source.Append(')');
        }

        source.AppendLine(")] ");
    }

    static string RenderTypeOf(INamedTypeSymbol type) {
        if (!IsDefinitionWithTypeParameters(type)) {
            return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        var builder = new StringBuilder("global::");
        if (!type.ContainingNamespace.IsGlobalNamespace) {
            builder.Append(string.Join(
                ".",
                GetNamespaceParts(type.ContainingNamespace).Select(EscapeIdentifier)));
            builder.Append('.');
        }

        var containingTypes = new Stack<INamedTypeSymbol>();
        for (var current = type; current is not null; current = current.ContainingType) {
            containingTypes.Push(current);
        }

        while (containingTypes.Count > 0) {
            var current = containingTypes.Pop();
            builder.Append(EscapeIdentifier(current.Name));
            if (current.Arity > 0) {
                builder.Append('<');
                builder.Append(',', current.Arity - 1);
                builder.Append('>');
            }

            if (containingTypes.Count > 0) {
                builder.Append('.');
            }
        }

        return builder.ToString();
    }

    static bool IsDefinitionWithTypeParameters(INamedTypeSymbol type) {
        for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType) {
            if (current.Arity > 0 && current.TypeArguments.All(argument => argument.TypeKind == TypeKind.TypeParameter)) {
                return true;
            }
        }

        return false;
    }

    static IEnumerable<string> GetNamespaceParts(INamespaceSymbol @namespace) {
        var parts = new Stack<string>();
        for (var current = @namespace; !current.IsGlobalNamespace; current = current.ContainingNamespace) {
            parts.Push(current.Name);
        }

        return parts;
    }

    static string EscapeIdentifier(string identifier) => "@" + identifier;

    static string GetSortName(INamedTypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    static Location GetLocation(INamedTypeSymbol type) =>
        type.Locations.FirstOrDefault(location => location.IsInSource) ?? Location.None;

    sealed class MethodBodyInfo {
        public HashSet<ITypeSymbol> QueryTypes { get; } = new(SymbolEqualityComparer.Default);

        public HashSet<IMethodSymbol> Invocations { get; } = new(SymbolEqualityComparer.Default);
    }

    sealed class GenerationResult {
        public GenerationResult(string? source, ImmutableArray<Diagnostic> diagnostics) {
            Source = source;
            Diagnostics = diagnostics;
        }

        public string? Source { get; }

        public ImmutableArray<Diagnostic> Diagnostics { get; }

        public static GenerationResult Empty { get; } = new(null, ImmutableArray<Diagnostic>.Empty);
    }
}
