<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <RootNamespace>HCommons.Reflection.Tests.Fixture</RootNamespace>
    </PropertyGroup>

</Project>
