<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <RootNamespace>HCommons.Reflection.Tests.Fixture</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HCommons.Reflection\HCommons.Reflection.csproj" />
        <ProjectReference Include="..\HCommons.Reflection.SourceGeneration\HCommons.Reflection.SourceGeneration.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
